apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stockpit-api
  namespace: stockpit
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: stockpit-api
  endpoints:
    - port: http              
      path: /metrics
      interval: 15s